### ISSUE TITLE
"Go" button seems to be useless

### ISSUE THREAD

**Issue by sylvainar** [WikiJourney/wikijourney_app#39] opened 2015-08-26 13:55 UTC
When I type a destination and then click on "Go", the app looks for POIs around me...

**Comment by nymous** [comment] 2015-09-02 16:28
This is not a bug, it is not implemented...

**Comment by sylvainar** [comment] 2015-09-09 07:34
Lol x)

**Comment by sylvainar** [comment] 2015-09-09 07:40
Okay no problem

**Comment by nymous** [comment] 2015-12-04 18:04
Fixed in 7d17b754266abbd54b61a57da19a23538585e845

**Closed as completed by nymous** 2015-12-04 18:04 UTC
Labels: feature
